### ISSUE TITLE
angular2 with ES6 should not reference es6-promise

### ISSUE THREAD

**Issue by maffoo** [borisyankov/DefinitelyTyped#5015] opened 2015-07-21 23:25 UTC
When targeting ES6 with the new typescript 1.5.3, the es6-promise definitions referenced in angular2.d.ts conflict with the promise definition built in to the es6 library definitions, giving a duplicate identifier error:

```
$ tsc
/usr/local/lib/node_modules/typescript/bin/lib.es6.d.ts(4775,11): error TS2300: Duplicate identifier 'Promise'.
/usr/local/lib/node_modules/typescript/bin/lib.es6.d.ts(4855,13): error TS2300: Duplicate identifier 'Promise'.
typings/es6-promise/es6-promise.d.ts(11,15): error TS2300: Duplicate identifier 'Promise'.
typings/es6-promise/es6-promise.d.ts(42,16): error TS2300: Duplicate identifier 'Promise'.
```

If I remove the reference to es6-promise.d.ts in angular2.d.ts, everything compiles fine. I don't know what the best way is to handle situations like this, but perhaps having a separate angular2-es6.d.ts would work. This would basically be the existing definitions, without the reference to es6-promise. angular2.d.ts would then just reference es6-promise and angular2-es6.

**Comment by lorem--ipsum** [comment] 2015-08-23 16:55
Same problem here.

**Comment by vvakame** [comment] 2015-08-25 16:47
@alexeagle ?

**Comment by alexeagle** [comment] 2015-08-25 17:40
This is a bit tricky because typescript doesn't support different referenced typings depending on the --target. See https://github.com/Microsoft/TypeScript/issues/3215 for discussion at the language level.

I dealt with this in angular's build in https://github.com/angular/angular/commit/643c71740e9e0a325f2f3b8431eb5f67cd84ba56

Basically what has to happen is: any es6 shims must be un-referenced in the sources, and just provided to the compiler when targeting es5.
So indeed, it's incorrect for es6-promise.d.ts to be appearing as an input to the compiler.

If we solved this the same way as angular, we'd remove the ///reference to es6-promise, and anyone compiling with target ES5 would have to include that file explicitly in the compiler inputs (eg. in their `tsconfig.json`) but I'm concerned since that's the common getting-started use case, and would cause a lot of new users trouble.

Your suggestion of distributing both a `angular2.d.ts` and `angular2-es6.d.ts` is feasible and easy, but it would be a pity to add the complexity of presenting both files to users when the only difference is this one line. Also it's not forward-compatible to a proposal like https://github.com/Microsoft/TypeScript/issues/4423

In the short term, the best workaround is probably to check in the typings/ directory in your source control, and make that local edit to remove the es6-promise reference.

**Comment by tkrotoff** [comment] 2015-10-22 10:05
The problem is not specific to `angular2.d.ts`.

If you (or one of your dependency) reference multiple Promise implementation definition (i.e `es6-promise.d.ts`, `bluebird.d.ts`, `lib.es6.d.ts` and probably others) => BOOM

This can lead to some cleanup.
I think `es6-promise.d.ts` should be removed: the [GitHub project](https://github.com/jakearchibald/ES6-Promise) says _"This is a polyfill of the ES6 Promise"_. By definition it should be the same API as `lib.es6.d.ts` (differences are bugs).

FYI [Bluebird](https://github.com/petkaantonov/bluebird) is not a polyfill and thus `bluebird.d.ts` is needed.

This can be generalized: all definitions for libraries that just polyfill ES6/2015 features (ES7 too?) should be removed from DefinitelyTyped.

**Comment by alexeagle** [comment] 2015-10-23 22:59
I created a `--target es6`-compatible typing file at
https://github.com/angular/angular/blob/master/modules/angular2/manual_typings/globals-es6.d.ts

We only need a small change in Angular to add something like `angular2-es6.d.ts` at the top level which would not export any symbols that conflict with `lib.es6.d.ts`.

**Comment by alexeagle** [comment] 2015-10-23 23:00
Since angular2 is no longer on definitely typed, I'm moving this issue to https://github.com/angular/angular/issues/4882

**Closed by alexeagle** 2015-10-23 23:00 UTC

**Comment by jfstephe** [comment] 2015-10-27 11:30
Sorry but why is this closed? As @tkrotoff mentioned, this isn't specific to angular, so the root cause isn't fixed. Committing the type definitions into VCS shouldn't be an acceptable solution IMHO.
Don't get me wrong, this is good stuff and I'm appreciative of the efforts. [:-)
bluebird and es6-promises are used on a (yeoman generated) background project and I've started getting this error recently (not sure why only recently).

**Comment by alexeagle** [comment] 2015-10-27 16:46
I closed this issue because it was about angular2 typings.
I think the right issue to address your problem is https://github.com/Microsoft/TypeScript/issues/3215

**Comment by dc0d** [comment] 2016-01-10 12:00
This error still exists. Getting 'whatwg-fetch' package using `tsd install whatwg-fetch --save` (today):

![error](https://cloud.githubusercontent.com/assets/3826814/12221414/08997342-b7af-11e5-9267-949499db6ccb.jpg)

**Comment by jasonswearingen** [comment] 2016-01-17 07:16
Here is the solution you guys should do, and it really is ***the best solution***

inside the angular2 module, add an ```IPromise``` interface, such as what I do in this checkin: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/7666/files
and then change all the Promise references to your new internal ```IPromise``` interface.

This adds a Promise "shape" without explictly requiring any particular Promise library.

Let me know if the solution is not clear to you.  Hope it helps.

**Comment by alexeagle** [comment] 2016-02-13 05:05
@jasonswearingen I used your idea for the dependency on zone.js, but not for es6-promise. The reason is that we expose Promise in our external APIs, so users editor would show completions for angular2 "IPromise". It's structurally typed and therefore will type-check, but it looks ugly to show the user that we return something when it's not clearly castable to the type they expect. Also some users may take this literally and start using angular2 "IPromise" type in their code since it comes through our API, which works in a type position, but not in a value position (eg. `new IPromise()`) so I think that would be confusing.

Anyway we don't export any of the dependent typings anymore.
