### ISSUE TITLE
jquery.d.ts 2.2.3 not compatible with kendo.all.d.ts

### ISSUE THREAD

**Issue by darkthread** [borisyankov/DefinitelyTyped#3976] opened 2015-03-27 01:34 UTC
After upgraded to version 2.2.3, jquery.d.ts failed to compile and throw this error in my VS2013 with TypeScript tool 1.4:
Error 545	Interface 'JQueryPromise<T>' incorrectly extends interface 'JQueryGenericPromise<T>'.
  Types of property 'then' are incompatible.
    Type '(doneCallbacks: any, failCallbacks: any, progressCallbacks?: any) => JQueryPromise<T>' is not assignable to type '{ <U>(doneFilter: (value?: T, ...values: any[]) => U | JQueryPromise<U>, failFilter?: (...reasons...'.
      Type 'JQueryPromise<T>' is not assignable to type 'JQueryPromise<void>'.
        Type 'T' is not assignable to type 'void'.	X:\Web\Scripts\typings\jquery\jquery.d.ts	 @ Lines: 304	Column: 11	

Use Package Management Console reinstall version 2.2.2, it works fine. Is it a bug of 2.2.3?

**Comment by vvakame** [comment] 2015-03-29 10:29
@johnnyreilly ?

**Comment by johnnyreilly** [comment] 2015-03-29 13:04
I don't know what to say... the tests pass? I'll try the latest typing file on a project of mine and see what happens. Ping me if I forget to report back

**Comment by MartinF** [comment] 2015-03-30 23:27
I get a lot of errors as well.
I am also running VS 2013 and TypeScript 1.4

**Comment by johnnyreilly** [comment] 2015-03-31 05:04
@darkthread Could you provide a sample of code that errors with 2.2.3 but not with 2.2.2? I'm planning to revert to 2.2.2 and add a test with your code that prevents the issue being reintroduced. Of course if you'd be willing to submit a PR to do this it would be gratefully received!

**Comment by david-hollifield** [comment] 2015-03-31 20:11
I was also getting these build errors. I had to install the the latest TypeScript tools (1.4) then, after clicking on a build error, allowed VS2013 to upgrade my project to the latest TypeScript version. Make sure your csproj has the <TypeScriptToolsVersion>1.4</TypeScriptToolsVersion> entry. My build errors went away after that.

**Comment by darkthread** [comment] 2015-03-31 21:31
@johnnyreilly I found that the issue happened when using Kendo UI's TypeScript definition, kendo.all.d.ts, with jQuery definition 2.2.3, but I am not sure which definition should be modified.  

Here is a simple project to reproduce the issue: https://www.dropbox.com/s/qfemleptefy5stp/JQTSTest.zip?dl=0

![image](https://cloud.githubusercontent.com/assets/572199/6929761/02e4ee22-d830-11e4-886a-f99d41b60091.png)

**Comment by johnnyreilly** [comment] 2015-04-01 09:27
Hi @darkthread,

It looks like the issue is with `kendo.all.d.ts` - specifically this section of code: 

```
interface JQueryPromise<T> {
    pipe(doneFilter?: (x: any) => any, failFilter?: (x: any) => any, progressFilter?: (x: any) => any): JQueryPromise<T>;
    then(doneCallbacks: any, failCallbacks: any, progressCallbacks?: any): JQueryPromise<T>;
}
```

If you comment these lines out the problem disappears.

Kendo isn't one of DT's typings so I guess you should take this up with Telerik.  I suspect it's an easy fix that relates to the changes @falsandtru made [here](https://github.com/borisyankov/DefinitelyTyped/pull/3887).  

I'm going to close this issue as it's not Definitely Typed related.  I've renamed the issue for visibility of anyone else who might stumble on this.  

Thanks for the repro - very helpful.

Best,
John

**Closed by johnnyreilly** 2015-04-01 09:27 UTC

**Comment by darkthread** [comment] 2015-04-01 09:37
@johnnyreilly Thanks.  I have reported this issue with a link to this issue to Telerik forum earlier today.
With your investigation, I think Telerik can fix it soon .  Thanks again.

**Comment by mikecole** [comment] 2015-04-15 16:39
@darkthread Can you post the link to Telerik's response to help searchers in the future? Thank you.

**Comment by darkthread** [comment] 2015-04-16 22:14
@mikecole already done two weeks ago and Telerik is [trying to resolve  it](http://www.telerik.com/forums/compilation-error-for-kendo-all-d-ts-and-jquery-d-ts-2-2-3#dqfXO1MjWUCRopSyUtQaFw).

**Comment by tsvetomir** [comment] 2015-06-08 15:26
After a bit of delay this is fixed in the Kendo UI TypeScript definitions as well. I'll follow with a PR.
