### ISSUE TITLE
jQuery .grep() does not accept jQuery. argument type is array.

### ISSUE THREAD

**Issue by yadimon** [borisyankov/DefinitelyTyped#5472] opened 2015-08-21 11:13 UTC
this code shows type error in PHPStorm:

var selected = $("div");
var filtered = $.grep(selected, function(){});

in jquery.t.ds grep 1. argument is defined as `T[]`, array. (https://github.com/borisyankov/DefinitelyTyped/blob/master/jquery/jquery.d.ts#L1003)
But jQuery selected values is an array too + jquery properties.

**Comment by vvakame** [comment] 2015-08-21 15:37
@johnnyreilly

**Comment by johnnyreilly** [comment] 2015-08-25 13:25
Hi,

There's not enough information here to go on I'm afraid.  Closing for now.

**Closed by johnnyreilly** 2015-08-25 13:25 UTC

**Comment by yadimon** [comment] 2015-08-25 18:25
Hi,
what information is required?

**Comment by johnnyreilly** [comment] 2015-08-25 19:28
Could you be a little clearer about what the problem is?  I'm afraid I didn't quite understand your meaning.

**Comment by yadimon** [comment] 2015-08-26 00:30
intellij (PHPStorm) uses this definitions here, for code quality check.

if i write there this code:
```javascript
var selected = $("div");
var filtered = $.grep(selected, function(e,i){/* do somethinng */});
```
it works properly and is right.

But Intellij shows me error, for type check.

The error is showed because the `selected` variable is of type `JQuery` and the `$.grep()` function's first argument is defined by [jquery.t.ds L1003](https://github.com/borisyankov/DefinitelyTyped/blob/master/jquery/jquery.d.ts#L1003) as `T[]` array.
But! The `JQuery` type is an array + object properties in javascript.
So it can be passed to the `grep()`function. Should not show any errors.
The definition in jquery.d.ts should be fixed for the `grep()` function

i see all this first time, but i think something like this should be added to `grep`:
`grep(obj: JQuery, func: (elementOfArray: Element, indexInArray: number) => boolean, invert?: boolean): Element[];`
i can make a pull request for this issue.

**Comment by johnnyreilly** [comment] 2015-08-26 05:07
I see the problem. Whilst what you're doing works, it's not behaviour officially supported by jquery. Our typings aim to be spec compliant. According to the spec it's only arrays that are catered for: http://api.jquery.com/jquery.grep/

If you can get the API docs changed (it's on GitHub) then we could happily accept a PR on this, but not until. Good luck!

**Comment by yadimon** [comment] 2015-08-26 22:17
there is still problem with ArrayLikeObject type overall.
e.g. http://api.jquery.com/jquery.merge/
`merge` has arguments as `ArrayLikeObject` in the jQuery api,
but https://github.com/borisyankov/DefinitelyTyped/blob/master/jquery/jquery.d.ts#L1085
accepts only pure arrays.

this code is ok, but shows errors:
```javascript
var arrayLikeObject = $("div");
var arr = [1,2,3];
$.merge(arr, arrayLikeObject)
```

is there any ArrayLikeObject typescript type?
