### ISSUE TITLE
angular-scenario causes compilation issue in VS2013

### ISSUE THREAD

**Issue by HarelM** [borisyankov/DefinitelyTyped#3878] opened 2015-03-15 22:59 UTC
Hi, I have just updated today the definitelytyped package from nuget and I hitnk there is an issue with angular.scenario.d.ts:
it starts with:
```javascript
declare module ng {
    export interface IAngularStatic {
        scenario: any;
    }
}
```
while all the other files starts with:
```javascript
declare module angular { ... }
```
changing this from ng to angular solves compilation issues:
"Import declaration conflicts with local declaration of 'ng'"

Thanks,
Great project by the way! keep on the good work!

**Comment by gildorwang** [comment] 2015-03-16 16:39
Hit this issue too. The project could not build. The issue is not only with my own code, but also the `.d.ts` files from NuGet. I fixed by changing all `ng` into `angular` in all files, and removed the following line from `angular.d.ts`: 

````TypeScript
 // Collapse angular into ng
import ng = angular;
````

Why is `ng` still used in those `d.ts` files? Please fix this build break!

**Comment by HarelM** [comment] 2015-03-16 16:57
The line of code
```javascript 
import ng = angular;
```
is relevant for backwards compatibility - removing it makes you have to change your code from ```ng``` to ```angular```.
I too updated all my code to use ```angular``` instead of ```ng``` but that was only because I didn't like ```ng``` before.

**Comment by gildorwang** [comment] 2015-03-17 03:13
Apparently it did not work. I got a build error saying `Import declaration conflicts with local declaration of 'ng'`.

**Comment by gildorwang** [comment] 2015-03-20 14:56
I've found the reason. It's actually because I have extended the interface in my code. My fault. Sorry for this!

**Comment by alexknips** [comment] 2015-04-28 09:41
I had the same problem.
I had to delete the declaration file of angular-mocks which extended the IAngularStatic interface and lead to this problem in the first place 

https://github.com/borisyankov/DefinitelyTyped/blob/master/angularjs/angular-mocks.d.ts

```javascript
    interface IAngularStatic {
        mock: IMockStatic;
    }
```

**Comment by Mellbourn** [comment] 2015-05-29 15:23
Is "ng" really obsolete?

**Comment by bgever** [comment] 2015-06-24 10:22
`ng` is still defined as a valid alias in the definitions, @Mellbourn.

What caused this issue for me was a `declare module ng` in our own code. Just like @basarat mentions in referenced issue #258.

Working around that definition override solved the issue for me. The v1.4 definition file is backward compatible with `ng` references. However, I only found this out after renaming all hundreds of `ng` references to `angular`... Ah well, had to be done someday anyway! :smile:

**Comment by basarat** [comment] 2015-06-24 22:32
Closing as details of how to upgrade are mentioned https://github.com/borisyankov/DefinitelyTyped/pull/3851Please update  *all* definitions.

**Closed by basarat** 2015-06-24 22:32 UTC

**Comment by PascalSenn** [comment] 2015-10-09 09:04
I run into the same issue. 

The trouble caused by the legacy folder in agnular. Check your dependencies if you have this issue.
